WA for release-4.15 opm (#13476)

diff --git a/pipeline/setup-vm b/pipeline/setup-vm
--- a/pipeline/setup-vm
+++ b/pipeline/setup-vm
@@ -151,12 +151,13 @@ fi
 
 
 #get opm client
+<< EOF
 if echo $INSTALL_TOOLS | grep -i 'opm' > /dev/null; then
     echo "------------------get opm------------------------"
     echo "get latest opm"
     echo "set env http_proxy https_proxy"
     unset http_proxy https_proxy
-    curl -s -k -L https://mirror2.openshift.com/pub/openshift-v4/x86_64/clients/ocp/candidate-4.14/opm-linux.tar.gz -o opm-linux.tar.gz
+    curl -s -k -L https://mirror2.openshift.com/pub/openshift-v4/x86_64/clients/ocp/candidate-4.15/opm-linux.tar.gz -o opm-linux.tar.gz
     tar -xzvf opm-linux.tar.gz
     echo "get opm-linux.tar.gz successfully"
     rm -f opm-linux.tar.gz
@@ -168,6 +169,30 @@ if echo $INSTALL_TOOLS | grep -i 'opm' > /dev/null; then
         exit 1
     fi
 fi
+EOF
+if echo $INSTALL_TOOLS | grep -i 'opm' > /dev/null; then
+    echo "------------------get opm------------------------"
+    echo "get latest opm"
+    echo "set env http_proxy https_proxy"
+    unset http_proxy https_proxy
+    
+    rm -rf ${WORKSPACE}/opm
+    mkdir ${WORKSPACE}/opm
+    git clone git@github.com:openshift/operator-framework-olm.git ${WORKSPACE}/opm
+    cd ${WORKSPACE}/opm
+    git checkout release-4.15
+    make bin/opm
+    mv bin/opm -f $WORKDIR
+    echo "opm version:"
+    opm version
+    retVal=$?
+    if [ $retVal -ne 0 ]; then
+        echo "get opm failed"
+        exit 1
+    fi
+fi
+
+
 
 cp -f ~/.docker/auto/config.json ~/.docker
 podman login quay.io
